apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saleor
  template:
    metadata:
      labels:
        app: saleor
    spec:
      containers:
      - name: saleor-api
        image: saleor/saleor:3.0
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: postgres://saleor:saleor@db/saleor
        - name: REDIS_URL
          value: redis://redis:6379/0
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"
      - name: saleor-dashboard
        image: saleor/dashboard:3.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
