version: '3.8'

services:
  api:
    image: saleor/saleor:3.0
    environment:
      DATABASE_URL: postgres://saleor:saleor@db/saleor
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  dashboard:
    image: saleor/dashboard:3.0
    ports:
      - "9003:80"
    depends_on:
      - api

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: saleor
      POSTGRES_USER: saleor
      POSTGRES_PASSWORD: saleor
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

