apiVersion: v1
kind: Service
metadata:
  name: saleor-api-service
spec:
  selector:
    app: saleor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: saleor-dashboard-service
spec:
  selector:
    app: saleor
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 80
  type: LoadBalancer
